apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  clusterIP: None
  ports:
  - name: amqptls
    port: 5671
    protocol: TCP
    targetPort: 5671
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: 4369
  - name: http
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  - name: mqtttls
    port: 8883
    protocol: TCP
    targetPort: 8883
  selector:
    app: rabbitmq
  sessionAffinity: None
  type: ClusterIP